# Generated by Django 2.1.1 on 2018-09-21 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dashboard', '0002_auto_20180921_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mcq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=250)),
                ('choice1', models.CharField(max_length=100)),
                ('choice2', models.CharField(max_length=100)),
                ('choice3', models.CharField(max_length=100)),
                ('choice4', models.CharField(max_length=100)),
                ('correct_choice', models.CharField(max_length=100)),
                ('question_created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('question_updated_timestamp', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Video')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_taken', models.BooleanField(default=False)),
                ('quiz_marks', models.IntegerField(default=0)),
                ('quizquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Mcq')),
            ],
        ),
    ]
