# Generated by Django 2.1.1 on 2018-09-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_auto_20180921_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_logo_url',
            field=models.CharField(default='SOMEURL', max_length=1000),
        ),
    ]
